ERRCODE(SCIDB_LE_OP_COPYARRAY_ERROR1,                SCIDB_USER_ERROR_CODE_START+1);
ERRCODE(SCIDB_LE_OP_COPYARRAY_ERROR2,                SCIDB_USER_ERROR_CODE_START+2);
ERRCODE(SCIDB_LE_OP_COPYARRAY_ERROR3,                SCIDB_USER_ERROR_CODE_START+3);

ERRCODE(SCIDB_LE_OP_MATRICIZE_ERROR1,                SCIDB_USER_ERROR_CODE_START+4);
ERRCODE(SCIDB_LE_OP_MATRICIZE_ERROR2,                SCIDB_USER_ERROR_CODE_START+5);

ERRCODE(SCIDB_LE_OP_EIGEN_ERROR1,                	 SCIDB_USER_ERROR_CODE_START+6);
ERRCODE(SCIDB_LE_OP_EIGEN_ERROR2,                	 SCIDB_USER_ERROR_CODE_START+7);
ERRCODE(SCIDB_LE_OP_EIGEN_ERROR3,                	 SCIDB_USER_ERROR_CODE_START+8);
ERRCODE(SCIDB_LE_OP_EIGEN_ERROR4,                	 SCIDB_USER_ERROR_CODE_START+9);
ERRCODE(SCIDB_LE_OP_EIGEN_ERROR5,                	 SCIDB_USER_ERROR_CODE_START+10);
